name: 'Release'
on:
  push:
    tags:
      - v*
jobs:
  release-sud:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - run: mkdir sud_${{ steps.tagName.outputs.tag }}
    - name: Build MacOS Release
      run: |
        go build -o sud_${{ steps.tagName.outputs.tag }}/sud .
    - name: Build Windows Release
      run: |
        GOOS=windows GOARCH=amd64 go build -o sud_${{ steps.tagName.outputs.tag }}/sud.exe .
    - name: Set SHA
      id: shasum
      run: |
        echo ::set-output name=sha_osx::"$(shasum -a 256 sud_${{ steps.tagName.outputs.tag }}/sud | awk '{printf $1}')";
        echo ::set-output name=sha_windows::"$(shasum -a 256 sud_${{ steps.tagName.outputs.tag }}/sud.exe | awk '{printf $1}')"
    - name: Move
      run: |
        mv sud_${{ steps.tagName.outputs.tag }}/sud sud_${{ steps.tagName.outputs.tag }}/sud${{ steps.shasum.outputs.sha_osx }};
        mv sud_${{ steps.tagName.outputs.tag }}/sud.exe sud_${{ steps.tagName.outputs.tag }}/sud${{ steps.shasum.outputs.sha_windows }}.exe
    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset OSX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: sud_${{ steps.tagName.outputs.tag }}/sud${{ steps.shasum.outputs.sha_osx }}
        asset_name: sud-${{ steps.shasum.outputs.sha_osx }}
        asset_content_type: application/binary
    - name: Upload Release Asset Windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: sud_${{ steps.tagName.outputs.tag }}/sud${{ steps.shasum.outputs.sha_windows }}.exe
        asset_name: sud.exe
        asset_content_type: application/binary
    - name: Bump Brew
      uses: mislav/bump-homebrew-formula-action@v1
      env: 
        COMMITTER_TOKEN: ${{ secrets.BREW_TOKEN }}
      with:
        formula-name: sud
        homebrew-tap: yext/homebrew-tap
        download-url: https://github.com/yext/sud/releases/download/${{ steps.get_version.outputs.version }}/sud-${{ steps.shasum.outputs.sha_osx }}